"""team and board relationship

Revision ID: 57931b6208f6
Revises: 9bc06e50bc90
Create Date: 2023-07-22 22:57:58.898442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57931b6208f6'
down_revision = '9bc06e50bc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board', 'team', ['team_id'], ['id_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'team_id')
    # ### end Alembic commands ###
