"""team_id for member and ticket

Revision ID: b507969cd9d7
Revises: 57931b6208f6
Create Date: 2023-07-25 19:21:27.779054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b507969cd9d7'
down_revision = '57931b6208f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'member', 'team', ['team_id'], ['id_id'])
    op.add_column('ticket', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'team', ['team_id'], ['id_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'team_id')
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_column('member', 'team_id')
    # ### end Alembic commands ###
